stages:
  - build
  - review
  - staging
  - production

.doc:
  stage: build
  image: $DOC
  script:
    - make -C $base install DESTDIR=$CI_PROJECT_DIR/public
  artifacts:
    paths:
      - public

# The child pipeline needs at minimum one job to run - otherwise the sub-pipeline fails
webframe:
  stage: build
  image: $DOC
  script:
    - cp -rTu /DocBook/webframe public
  artifacts:
    paths:
      - public

.publish:
  variables:
    GIT_STRATEGY: none
  tags:
    - omar

review:
  stage: review
  extends: .publish
  script:
    - rsync -av --delete public/ /var/univention/buildsystem2/test_mirror/ftp/download/docs.$CI_BUILD_REF_SLUG
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: http://apt.knut.univention.de/download/docs.$CI_BUILD_REF_SLUG/
    on_stop: stop_review
    auto_stop_in: 1 week
  only:
    - branches
  except:
    - master

stop_review:
  stage: staging
  extends: .publish
  script:
    - rm -rf /var/univention/buildsystem2/test_mirror/ftp/download/docs.$CI_BUILD_REF_SLUG
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop

staging:
  stage: staging
  extends: .publish
  script:
    - rsync -av --delete public/ /var/univention/buildsystem2/test_mirror/ftp/download/docs
  environment:
    name: staging
    url: http://apt.knut.univention.de/download/docs/
  only:
    - master

production:
  stage: production
  extends: .publish
  script:
    - rsync -av public/ /var/univention/buildsystem2/test_mirror/ftp/download/docs
  environment:
    name: production
    url: http://updates.knut.univention.de/download/docs/
  when: manual
  only:
    - master
