stages:
  - build
  - deploy

.doc:
  stage: build
  image: $DOC
  script:
    - make -C $base install DESTDIR=$CI_PROJECT_DIR/public
  artifacts:
    paths:
      - public

# The child pipeline needs at minimum one job to run - otherwise the sub-pipeline fails
webframe:
  stage: build
  image: $DOC
  script:
    - cp -rTu /DocBook//webframe public
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  interruptible: no
  variables:
    GIT_STRATEGY: none
  script:
    - cd public
    - echo '<html><head><title>Documentation</title></head><body><ul>' >index.html
    - ls -1 *.html | sed 's,.*,<li><a href="&">&</a></li>,' >>index.html
    - echo '</ul></body></html>' >>index.html
  artifacts:
    paths:
      - public
