product: ucs
release: "5.0"
version: [6]
scope: ucs_5.0-0-errata5.0-6
src: univention-config-registry
fix: 15.0.11-1
desc: |
 This update addresses the following issues:
 * Fix traceback when `Interfaces()` is used with `ReadOnlyConfigRegistry()`.
bug: [56911]
