product: ucs
release: "5.0"
version: [2]
scope: ucs_5.0-0-errata5.0-2
src: univention-config-registry
fix:
desc: |
 This update addresses the following issues:
 * The UCR type checking is now displaying more specific information regarding
   the type constraints.
bug: [55573]
