product: ucs
release: "5.0"
version: [2]
scope: ucs_5.0-0-errata5.0-2
src: univention-config-registry
fix: 15.0.7-20A~5.0.0.202209291831
desc: |
 This update addresses the following issue:
 * Add validation for values of UCR variables. By default only a warning is
   printed if an invalid value is set. By setting the UCR variable
   `ucr/check/type` to `yes` type checking can be enforced, which will prevent
   invalid values to be set. As the type annotation of several UCR variables
   is currently wrong, types `int` and `bool` are ignored for now and will be
   fixed by future updates.
bug: [54495]
