product: ucs
release: "5.0"
version: [2]
scope: ucs_5.0-0-errata5.0-2
src: univention-config-registry
fix:
desc: |
 This update addresses the following issues:
 * A new variable type 'url_http' was added in order to support
   validation of http/https URL strings.
bug: [55044]
