product: ucs
release: "5.0"
version: [0]
scope: ucs_5.0-0-errata5.0-0
src: univention-config-registry
fix: 15.0.7-9A~5.0.0.202109101628
desc: |
 This update addresses the following issue:
 * Umlauts in UCR keys are allowed again, which was broken since UCS 5.0-0.
 * UCR now exits with an exit code of 1 when setting at least UCR variable
   fails.
bug: [53742]
erratum: 88
announced: 2021-09-15
